### ISSUE TITLE
System.BadImageFormatException: 'Format of the executable (.exe) or library (.dll) is invalid.'

### ISSUE THREAD

**Issue by NoSharpisCool** [OxideMod/Oxide.Patcher#136]
`AssemblyDefinition assembly = AssemblyDefinition.ReadAssembly(oldfile, new ReaderParameters { AssemblyResolver = resolver });;`
on line 739 of PatcherForm.
This is triggered when adding the 7 days to die dll to the assembly.

**Comment by lukespragg** [comment]
Works just fine with 7 days to die. If it can’t load a dll then that dll isn’t a valid .net dll.
